### ISSUE TITLE
Add undo/redo

### ISSUE THREAD

**Issue by zastrowm** [zastrowm/friendly-engine#4]
We should get this in from the beginning before we get too far; architecturally it'll need to be thought out.

## Tasks

 - [x] Create Command Layer
 - [x] Hook up keyboard shortcuts

**Comment by allenm84** [comment]
Nice!

**Comment by zastrowm** [comment]
Implemented keyboard shortcuts for undo/redo as part of c7e37ba.
Keyboard shortcuts will need to be revisited as we add more (https://wangchujiang.com/hotkeys/ looked interesting)
